import { boot } from 'quasar/wrappers'
import AppIcon from 'src/components/AppIcon.vue'
import {
  ArrowDownAZ,
  ArrowLeft,
  Baby,
  Book,
  Briefcase,
  BriefcaseMedical,
  Cake,
  Calendar,
  CalendarDays,
  Camera,
  Car,
  Check,
  ChevronDown,
  Church,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleQuestionMark,
  CircleX,
  Clock,
  Cloud,
  Download,
  Drama,
  Expand,
  Eye,
  EyeOff,
  File,
  FileLock,
  FilePen,
  FileSpreadsheet,
  FileText,
  Gavel,
  Grip,
  GripHorizontal,
  Guitar,
  HardHat,
  Heading,
  Heart,
  HeartHandshake,
  House,
  IdCard,
  Mail,
  MapPin,
  Mars,
  Menu,
  MessageCircle,
  MessagesSquare,
  Mic,
  Minus,
  Music,
  NotebookPen,
  Palette,
  Pen,
  Pencil,
  PersonStanding,
  Phone,
  Pilcrow,
  Plus,
  Presentation,
  Printer,
  Save,
  Search,
  Shrink,
  Signature,
  SquareCheck,
  SquarePen,
  Star,
  Smartphone,
  Tent,
  TentTree,
  Trash2,
  Type,
  User,
  UserCog,
  Users,
  Utensils,
  Venus,
  Wrench,
  X,
  Zap
} from '@lucide/vue'

export const iconRegistry = {
  'arrow-down-a-z': ArrowDownAZ,
  'arrow-left': ArrowLeft,
  'bars': Menu,
  'bolt': Zap,
  'book-atlas': Book,
  'briefcase': Briefcase,
  'cake': Cake,
  'cake-candles': Cake,
  'calendar': Calendar,
  'calendar-alt': CalendarDays,
  'camera': Camera,
  'campground': TentTree,
  'car': Car,
  'car-side': Car,
  'caret-down': ChevronDown,
  'chalkboard-user': Presentation,
  'check': Check,
  'check-circle': CircleCheck,
  'check-square': SquareCheck,
  'children': Baby,
  'church': Church,
  'circle': Circle,
  'circle-check': CircleCheck,
  'circle-question': CircleQuestionMark,
  'circle-xmark': CircleX,
  'cloud': Cloud,
  'comment': MessageCircle,
  'comments': MessagesSquare,
  'compress': Shrink,
  'download': Download,
  'edit': SquarePen,
  'envelope': Mail,
  'exclamation-circle': CircleAlert,
  'expand': Expand,
  'eye': Eye,
  'eye-slash': EyeOff,
  'file': File,
  'file-edit': FilePen,
  'file-excel': FileSpreadsheet,
  'file-lines': FileText,
  'file-shield': FileLock,
  'file-signature': NotebookPen,
  'floppy-disk': Save,
  'font': Type,
  'grip': Grip,
  'grip-lines': GripHorizontal,
  'guitar': Guitar,
  'handcuffs': Gavel,
  'heading': Heading,
  'heart': Heart,
  'house-chimney': House,
  'id-card': IdCard,
  'location-dot': MapPin,
  'mars': Mars,
  'masks-theater': Drama,
  'microphone': Mic,
  'minus': Minus,
  'mobile': Smartphone,
  'mobile-screen-button': Smartphone,
  'music': Music,
  'palette': Palette,
  'paragraph': Pilcrow,
  'pen': Pen,
  'pen-to-square': SquarePen,
  'pencil': Pencil,
  'person-digging': HardHat,
  'person-half-dress': PersonStanding,
  'phone': Phone,
  'plus': Plus,
  'praying-hands': HeartHandshake,
  'print': Printer,
  'question-circle': CircleQuestionMark,
  'save': Save,
  'screwdriver-wrench': Wrench,
  'search': Search,
  'signature': Signature,
  'star': Star,
  'suitcase-medical': BriefcaseMedical,
  'tent': Tent,
  'times': X,
  'trash': Trash2,
  'user': User,
  'user-clock': Clock,
  'user-gear': UserCog,
  'users': Users,
  'users-rays': Users,
  'users-rectangle': Users,
  'utensils': Utensils,
  'venus': Venus,
  'xmark': X
}

export const fallbackIcon = CircleQuestionMark

const svgUri = (inner, stroke = 'currentColor') =>
  'img:data:image/svg+xml;utf8,' + encodeURIComponent(
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="${stroke}" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${inner}</svg>`
  )


const stringIconMap = {
  'check': svgUri('<path d="M20 6 9 17l-5-5"/>', '#fff'),
  'circle-check': svgUri('<circle cx="12" cy="12" r="10"/><path d="m9 12 2 2 4-4"/>', '#fff'),
  'check-circle': svgUri('<circle cx="12" cy="12" r="10"/><path d="m9 12 2 2 4-4"/>', '#fff'),
  'circle-xmark': svgUri('<circle cx="12" cy="12" r="10"/><path d="m15 9-6 6"/><path d="m9 9 6 6"/>', '#fff'),
  'exclamation-circle': svgUri('<circle cx="12" cy="12" r="10"/><path d="M12 8v4"/><path d="M12 16h.01"/>', '#fff'),
  'times': svgUri('<path d="M18 6 6 18"/><path d="m6 6 12 12"/>'),
  'xmark': svgUri('<path d="M18 6 6 18"/><path d="m6 6 12 12"/>')
}

export default boot(({ app }) => {
  app.component('AppIcon', AppIcon)

  const $q = app.config.globalProperties.$q
  $q.iconMapFn = (iconName) => {
    if (iconName in stringIconMap) {
      return { icon: stringIconMap[iconName] }
    }
    return undefined
  }
})
